import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { PaymentService } from '../services/payment.service';
import { ActivatedRoute, Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { CommonModule, NgIf } from '@angular/common';
interface PaymentResponse {
  redirectUrl: string;
}
@Component({
  selector: 'app-paymentgateway',
  standalone: true,
  imports: [FormsModule,ReactiveFormsModule,MatButtonModule,CommonModule,NgIf],
  schemas:[CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './paymentgateway.component.html',
  styleUrl: './paymentgateway.component.css'
})
export class PaymentgatewayComponent {

  constructor(private paymentService: PaymentService,private router:Router) {}
  orderDetails = {
    "orderId": "ORD123456",          // Unique order ID generated by your system
    "amount": 1000,                  // Transaction amount (in paise or your specified currency unit)
    "currency": "INR",               // Currency code (e.g., INR for Indian Rupees)
    "redirectUrl": "http://localhost:63320", // URL to redirect after payment success
    "cancelUrl": "http://localhost:63320",    // URL to redirect after payment failure/cancellation
    "merchantId": "3348993", // Your CCAvenue merchant ID
    "transactionType": "Sale",       // Transaction type (e.g., Sale, Refund)
    "customerDetails": {
      "name": "John Doe",             // Customer name
      "email": "john.doe@example.com", // Customer email
      "phone": "9876543210",          // Customer phone number
      "address": "123 Street, City",  // Customer address
      "city": "City Name",            // Customer city
      "state": "State Name",          // Customer state
      "zip": "123456"                 // Customer ZIP code
    }
  }



  initiatePayment() {
  
    this.paymentService.initiatePayment(this.orderDetails).subscribe(
      (PaymentResponse) => {
       
  
        // Assuming the external payment URL is part of the response
        const externalUrl = PaymentResponse; // Replace 'paymentUrl' with the actual key from the response
        console.log(PaymentResponse)
        
          // window.location.href = externalUrl;
       
      },
      (error) => {
        console.error('Error initiating payment:', error);
      }
    );
  }
  

}
